steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/wserver-go:latest'
      - '.'
  - name: 'gcr.io/$PROJECT_ID/wserver-go:latest'
    args: ['version']

images:
  - 'gcr.io/$PROJECT_ID/wserver-go:latest'
