steps:
#  - name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
#    args: ['-f', 'docker-compose.yaml', 'up', '-d', '--build']

  - name: 'gcr.io/$PROJECT_ID/wserver-go:latest'
    args: ['test', '-cover', '/go/src/wserver']

images: ['gcr.io/$PROJECT_ID/wserver-go:latest']
