version: '3'

services:

  wserver-go:
    build: .
    container_name: wserver-go
    entrypoint: "/go/bin/wserver"
    ports:
      - 8000:8000
    # tty: true
    # environment:
    #     - GOPATH=/go/src/
    # volumes:
#     - ./src:/go/
