apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
        listen 80;
        index index.php index.html;
        root /usr/share/nginx/html;
    }
  index.html: |
    <h3>Code.education Rocks.</h3>
