apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-rocks

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-rocks
    spec:
      containers:
        - name: nginx-rocks
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
              readOnly: true
            - mountPath: /usr/share/nginx/html
              name: nginx-conf
              readOnly: true

      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: index.html
                path: index.html
