apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-greeting

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-greeting
    spec:
      containers:
        - name: go-greeting
          image: efepimenta/go-wserver:latest
          command: ["/go/bin/wserver"]
          ports:
            - containerPort: 8000
